# Generated by Django 2.1.7 on 2019-03-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='People',
        ),
    ]
