# Generated by Django 2.1.7 on 2019-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
